name: Reusable Python Workflow

on:
  workflow_call:
    inputs:
      run-tests:
        required: true
        type: boolean
      run-lint:
        required: true
        type: boolean
      build-docker:
        required: true
        type: boolean

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lint:
    if: ${{ inputs.run-lint }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run flake8
        run: |
          pip install flake8
          flake8 app/

  test:
    if: ${{ inputs.run-tests }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          pip install pytest
          pytest tests/

  docker-build:
    if: ${{ inputs.build-docker }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t my-python-app:latest .
