name: Python CI Workflow

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python-ci:
    uses: ./.github/workflows/_reusable-python.yml
    with:
      run-tests: true
      run-lint: true
      build-docker: true
